# Generated by Django 3.2.4 on 2023-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='price',
        ),
        migrations.AddField(
            model_name='helper',
            name='number',
            field=models.PositiveBigIntegerField(default=2, verbose_name='Nomer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(max_length=4000, verbose_name='Natija nomi'),
        ),
    ]
