# Generated by Django 3.2.4 on 2023-07-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20230621_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['id'], 'verbose_name': 'Url Name', 'verbose_name_plural': 'Url Namelar'},
        ),
        migrations.AlterField(
            model_name='change',
            name='name',
            field=models.CharField(max_length=4000, verbose_name='url name'),
        ),
    ]
