# Generated by Django 3.2.4 on 2023-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_auto_20230703_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='photos/', verbose_name='rasm')),
                ('img', models.ImageField(upload_to='photos/', verbose_name='rasm')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
