# Generated by Django 3.2.4 on 2023-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['id'], 'verbose_name': 'Url Name'},
        ),
        migrations.AddField(
            model_name='change',
            name='platinum',
            field=models.CharField(default=2, max_length=40, verbose_name='yuqori  tarif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='premium',
            field=models.CharField(default=2, max_length=40, verbose_name='premium tarif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='simple_price',
            field=models.CharField(default=2, max_length=40, verbose_name='oddiy tarif'),
            preserve_default=False,
        ),
    ]
