# Generated by Django 3.2.4 on 2023-08-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0007_auto_20230811_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discord',
            options={'ordering': ['id'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='discord',
            name='image',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='name',
        ),
        migrations.AddField(
            model_name='discord',
            name='number',
            field=models.CharField(default=2, max_length=200, verbose_name='Azolar soni'),
            preserve_default=False,
        ),
    ]
