# Generated by Django 4.2.2 on 2024-02-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_auto_20230823_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord',
            name='number',
            field=models.CharField(max_length=400, verbose_name='Azolar soni'),
        ),
    ]
